### PR TITLE
Cleanup dependencies

### PR DESCRIPTION
**Pull request by pablopalacios**
- remove lodash
- remove coveralls
- replace body-parser with express.json
- replace istanbul with nyc

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by redonkulus** [comment]
Just have to remove coveralls from the GitHub action too.

**Comment by pablopalacios** [comment]
@redonkulus oh, I've just added it. But it seems that exactly right now, coveralls is under maintenance.

**Comment by redonkulus** [comment]
I dont think coveralls is working, I would just remove coveralls all together, its not really beneficial.

**Comment by pablopalacios** [comment]
@redonkulus I also removed the dependency on `qs`.

**Review by redonkulus — APPROVED** [review]
Nice work!

**Pull request merged**
