### PR TITLE
remove extra executeRequest

### PR DESCRIPTION
**Pull request by kaesonho**
@Vijar seems like there's an extra `excuteRequest`

### CODE REVIEW

**Comment by mridgway** [comment]
:+1:

**Comment by ktslwy** [comment]
:+1:

**Comment by Vijar** [comment]
:ship:

**Comment by MattHo** [comment]
:+1:

**Comment by kaesonho** [comment]
Miss one line coverage, it should be fine, let me merge and release a new version since executing service twice might cause issues.

**Pull request merged**
