### PR TITLE
Expose xhr object for aborts

### LINKED ISSUE #142: Return the request object from fetchr call
Return the request object that has been created while making a fetchr call. Similar to the following

```javascript
var req = 	fetchr
			    .read('data_service')
			    .params({id: ###})
			    .end(function (err, data, meta) {
			    // handle err and/or data returned from data fetcher in this callback
			    });
```

Incase if we have to abort the request, it can be easily done just by doing
```javascript
req.abort();
```

Currently, there is no way of aborting the request that has been made using fetchr. A better use case will be when using fetchr for a component like auto-suggestion box, where-in we can abort the fetchr service calls that are already made (as the user types) and only fetch the data for the final query which user has typed-in.

### PR DESCRIPTION
**Pull request by Vijar**
@redonkulus @mridgway @praveenbnsm

We actually can expose the xhr object with little effort, but it just won't work with our promise interface though.

Fixes #142

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
We should probably make a note of this in our docs as a limitation.

**Comment by Vijar** [comment]
@redonkulus added docs

**Comment by redonkulus** [comment]
👍

**Pull request merged**
