### PR TITLE
fetcher: improve error messages

### LINKED ISSUE #180: Provide more info on errors
In our app we are currently experiencing some regular errors where we aren't certain about the origin. Sadly the stacktrace from fetchr isn't helping:

```
HttpError: Invalid Fetchr Access
    at create (/nix/store/ic4fdwwfi6x7mkd1b3cig194f9s768nk-hc-web-node-modules-prod/node_modules/fumble/libs/fumble.http.js:11:12)
    at Object.createMethod [as badRequest] (/nix/store/ic4fdwwfi6x7mkd1b3cig194f9s768nk-hc-web-node-modules-prod/node_modules/fumble/libs/fumble.http.js:16:16)
    at /nix/store/ic4fdwwfi6x7mkd1b3cig194f9s768nk-hc-web-node-modules-prod/node_modules/fetchr/libs/fetcher.js:362:37
[...]
```

Looking at [fetchr.js:362`](https://github.com/yahoo/fetchr/blob/608b0591b49e048b4971d886030d6e5350482e05/libs/fetcher.js#L362):

```js
            if (!Fetcher.isRegistered(resource)) {
                error = fumble.http.badRequest('Invalid Fetchr Access', {
                    debug: 'Bad resource ' + sanitizeResourceName(resource)
                });
                error.source = 'fetchr';
                return next(error);
            }
```

So the `sanitizeResourceName(resource)` is what I think should definitely be displayed in the stacktrace above. Otherwise the information you retrieve is basically: "Something went wrong because of the resource i was trying to operate on - but i won't tell you which resource that was"

Any chance that this could be changed?

### PR DESCRIPTION
**Pull request by pablopalacios**
Closes #180 

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by pablopalacios** [comment]
@redonkulus I'm not sure if I'm introducing any break change by removing `debug` from the error object. I can put it back just in the way it is.

**Comment by redonkulus** [comment]
Let's keep the debug property in case any apps are relying on it for some reason.

**Comment by pablopalacios** [comment]
@redonkulus done.

**Review by redonkulus — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
