### PR TITLE
[#111] Add promise support

### PR DESCRIPTION
**Pull request by Vijar**
@redonkulus @mridgway 

TODO: Client side promise support

### CODE REVIEW

**Comment by KATT** [comment]
this would make me a very happy dev, my `async` fluxible actions would get so pretty when I can `await` my services

**Comment by lo1tuma** [comment]
Any progress on this?

**Comment by Vijar** [comment]
@lo1tuma I'll get back on this today :) Totally forgot about this.

**Comment by Vijar** [comment]
@redonkulus @mridgway Promises are ready :)

**Comment by redonkulus** [comment]
LGTM, lot of duplicate code between client and server, would be nice to minimize that and reduce risk of bugs or sync issues.

**Comment by Vijar** [comment]
I'll look into extracting the `Request` class into its own file and share between server/client.

**Comment by redonkulus** [comment]
Yup, that can be done in another PR @Vijar

**Comment by redonkulus** [comment]
Just get @mridgway do check this out first.

**Comment by mridgway** [comment]
lgtm

**Pull request merged**
